# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='upstream_repositories',
            field=models.ManyToManyField(related_name='_repository_upstream_repositories_+', to='packages.Repository'),
        ),
    ]
